compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: hostfile
  deepspeed_multinode_launcher: openmpi
  gradient_accumulation_steps: 0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: INDUCTOR
fsdp_config: {}
machine_rank: 0
main_process_ip: 172.23.63.249
main_process_port: 8000
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 2
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
